version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: keycloak_postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak_server
    command: start
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: '$MrbsBrt$ys'
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      # Add the following:
      KC_HOSTNAME: auth.panl.mrbstest.com
      KC_PROXY: edge
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      condition: service_healthy
    volumes:
      - ./keycloak_theme:/opt/keycloak/themes

volumes:
  postgres_data:

